### PR TITLE
Add "islandora_models" terms for Compound and Newspaper

### PR DESCRIPTION
**Pull request by noahwsmith**
Related to ongoing conversations about the need for System Models for both Compound Objects and Newspaper (parent objects, not issues. This PR contains two new entries for these types, but I expect others may have better URLs than I was able to come up with.

### CODE REVIEW

**Comment by nigelgbanks** [comment]
We've opted to use http://vocab.getty.edu/aat/300242735 for compounds atm, though we can switch. @kspurgin

**Comment by nigelgbanks** [comment]
Oh actually just realized `http://purl.org/coar/resource_type/c_1843` is the same as the collection object. In the claw 7.x migration module the taxonomy uri is used to determine uniqueness so that nodes can be mapped to the right type. Having two with the same uri may break migrations.

**Comment by noahwsmith** [comment]
Ok I'll make that update to use the Getty vocab then, so it'll be unique at least, and this can sit til @dannylamb has a chance to take a peek. I didn't realize that Collection used "other" - is that the correct URL for Collection, then? (not sure how much it matters, and I know I'm not the right person to make this decision. I did run across https://schema.org/Collection as I was clicking around earlier today, though)

**Comment by nigelgbanks** [comment]
My bad it wasn't collection it was binary that used it they were next to one another in the file and I made the wrong association. https://raw.githubusercontent.com/Islandora/islandora/8.x-1.x/migrate/tags.csv

**Comment by kspurgin** [comment]
Hey, I was out last week for the American Thanksgiving holiday. 

Using http://vocab.getty.edu/aat/300242735 for "Compound Object" is not a perfect fit or fully precise. But it's not any more ambiguous than using http://purl.org/coar/resource_type/c_1843 for "Binary," I don't think. If we are not going to manage a specifically defined Islandora vocabulary and URIs, we will always be smooshing some "good enough" URIs in for some concepts. If we are good with that trade-off, this seems fine to me.

**Comment by noahwsmith** [comment]
Ok, so then Compound sounds "good enough" with Nigel's recommended change, which I've made.

And I picked "https://schema.org/Newspaper" for Newspaper, which I imagine is also "good enough". 

Tagging @dannylamb again hopefully for approval?

**Comment by kspurgin** [comment]
https://schema.org/Newspaper for Newspaper seems better than "good enough" as it's a pretty clear/precise match unlike for Binary and Compound object 👍

**Comment by dannylamb** [comment]
I'm happy to pull this in for now, so long as we can guarantee we're shipping with some compound and newspaper functionality next time we release :)

**Review by dannylamb — APPROVED** [review]

**Pull request merged**
