### PR TITLE
Explicitly close fedora flysystem connections

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: None

See https://islandora.slack.com/archives/CM5PPAV28/p1634323444315000 for the problem description and https://islandora.slack.com/archives/CM5PPAV28/p1634827620002700?thread_ts=1634323444.315000&cid=CM5PPAV28 for the explanation.

# What does this Pull Request do?

Imagine you run a restaurant. Normally volume is low so you can allow guests to sit at their table as long as they wish after completing their meal. Now imagine that volume has jumped drastically and that guests hanging around after their meal is resulting in a massive table wait-times.

Flysystem/Fedora client/Guzzle was issuing requests to Fedora with Connections as 'keep alive' which kept them open long after they were done and absorbing all the available TCP connections resulting in an unresponsive server.

This PR explicitly tells the Fedora/Guzzle client to close the connection when it is done, freeing up connections for new requests.

# What's new?

Update the fedora getResource calls in the Flysystem adapter with header arrays to include `'Connection' => 'close'` .

* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? No.

# How should this be tested?

_Really, this should be good with just a smoke test. Spin up the PR and see that nothing breaks. Trying to test scalability issues can be a beast..._

* Spin up an Islandora site
* Download a bunch of original files using flysystem
* Observe that the TCP connections are starting to pile up.
* Restart Tomcat and see them all disappear.
* Apply the PR
* Download a bunch of original files using flysystem again
* Observe that the TCP connections remain reasonably low.

# Documentation Status

* Does this change existing behaviour that's currently documented? No.
* Does this change require new pages or sections of documentation? No.
* Who does this need to be documented for? N/A

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by elizoller** [comment]
tests maybe failing https://github.com/Islandora/islandora/runs/3966689557?check_suite_focus=true#step:14:25 ?

**Comment by seth-shaw-unlv** [comment]
Yeah, I don't know why it is complaining about a "Call to a member function getStatusCode() on null". I need to look into that after the IRIG meeting.

**Comment by seth-shaw-unlv** [comment]
Oh, wait, I'm an hour early for that meeting. I'll look into it now.

**Comment by seth-shaw-unlv** [comment]
Uh oh, it probably has to do with
```php
    if (class_exists(\GuzzleHttp\Psr7\Utils::class)) {
      $prophecy->getBody()->willReturn(\GuzzleHttp\Psr7\Utils::streamFor("DERP"));
    } else {
      $prophecy->getBody()->willReturn(\GuzzleHttp\Psr7\stream_for("DERP"));
    }
```

**Comment by seth-shaw-unlv** [comment]
The test prophecies didn't foresee the new calls with the headers. Tests should pass now. 🤞

**Comment by dannylamb** [comment]
> The test prophecies didn't foresee the new calls with the headers.

Best dad joke I've heard all day :crystal_ball:

**Review by elizoller — APPROVED** [review]
smoke tested: Pulled in and was able to read and write things to fedora

**Pull request merged**
