### PR TITLE
captions v2

### PR DESCRIPTION
**Pull request by elizoller**
GitHub Issue:
Islandora/documentation#1305
Islandora/documentation#1003
https://www.drupal.org/project/drupal/issues/3057144
https://www.drupal.org/project/drupal/issues/3056714

Other Relevant Links
Perhaps superseding https://github.com/Islandora/islandora/pull/743/files
Definitely supersedes https://github.com/Islandora/islandora_defaults/pull/44

# What does this Pull Request do?
Takes the work in the patch 16 here https://www.drupal.org/project/drupal/issues/3056714  
Allows a user to add a "track" to an audio or video media object which will play in the HTML5 player

# What's new?
* code related to the config in https://github.com/Islandora/islandora_defaults/pull/48
* new templates, fieldtype, fieldwidget, fieldformatters

# How should this be tested?
* spin up an islandora site
* pull in islandora_defaults PR https://github.com/Islandora/islandora_defaults/pull/48 and this islandora PR
* do a partial config import on the config/install directory of islandora_defaults
* cache clear
* add an audio and/or video node
* add an audio and/or video original file media attached to that node
* when the service file derivative is created, add a VTT caption file to that service file media in the new track field
* view the node - in the menu on the HTML5 player, you should be able to toggle on and off captions

# Additional Notes
* this does not have the poster/thumbnail feature i presented in https://github.com/Islandora/islandora_defaults/pull/44

# Interested parties
@Islandora/8-x-committers @Natkeeran

### CODE REVIEW

**Review by seth-shaw-unlv — APPROVED** [review]
Works as advertised! 👍

**Comment by kayakr** [comment]
@elizoller I can now add a `.vtt` track file to an audio service file but I find the default audio player in Chrome isn't showing the captions (there is a player toggle for captions, but even with captions selected, I don't see anything). In Firefox I see a CC symbol with strikethrough, and in Safari the default player doesn't seem to offer a captions toggle at all.
Can you advise re combinations of files/browser that work?

**Comment by elizoller** [comment]
It's just using HTML5 for the player, so most modern browsers should handle it. I will look into it - what kind of audio file are you using?

**Comment by kayakr** [comment]
@elizoller The files I used are audio.mp3 and transcript.vtt from https://umd-mith.github.io/webvtt-player/annotations.html

**Comment by elizoller** [comment]
@kayakr i have finally had a chance to look into this with more detail and discovered that, as far as i can tell, the HTML5 player for audio with captions either needs a custom CSS + JS implementation to display the captions OR be treated as a video (with minor CSS tweaks). i have tested this in my local, so i will try in the next week or so to get this into a cleaned up PR.

**Comment by kayakr** [comment]
@elizoller Cool, will be keen to see what you come up with, or whether it's easiest to embed something like webvtt-player...

**Comment by alxp** [comment]
I don't know about chrome but when I was messing with video and captions, adding a thumbnail image to the player to display would let the captions be shown on top of that.

**Pull request merged**
