### PR TITLE
Fix warning by checking whether key is set.

### PR DESCRIPTION
**Pull request by jasonhildebrand**
# What does this Pull Request do?

We are adding the drupal/flag module to our Islandora instance to allow end users to create bookmarks (favourites) for repository items.

We see the warning "Warning: Undefined array key "plugin_id" in islandora_preprocess_views_view_table() (line 523 of modules/contrib/islandora/islandora.module)" when accessing a view that the drupal/flag module provides.

This PR eliminates this warning by checking for the array key using isset() before trying to use it.

# How should this be tested?

The code modified is related to the "integer weight field" functionality.  Test that nothing is broken by testing the "Re-order children" page.

# Interested parties
@Islandora/committers

### CODE REVIEW

**Review by rosiel — COMMENTED** [review]
I'm trying to recreate your error, and I'm having trouble creating a view that uses a table, but doesn't have `options['plugin_id']`. Can you send me some hints, or a screenshot?

And/or, can you test if `$field->getPluginId()` works with your view? It would be a nicer way to do this if it solves the problem.

Thanks!

**Comment by jasonhildebrand** [comment]
Thanks, @rosiel for looking at this.

Yes, $field->getPluginId()  works and is cleaner.  It eliminates the warning and I tested that drag and drop sorting still works as expected. I have updated the PR.

In terms of reproducing the warning, I am attaching a few screenshots of my view where it occurs:

bookmarks-view
bookmarks-view-table-settings

**Comment by jasonhildebrand** [comment]
As mentioned, we are using the drupal/flag module to allow end users to create bookmarks (favourites) for repository items.  This view is what the drupal/flag module provides - we have made minimal changes if any.

**Comment by jasonhildebrand** [comment]
I don't think this makes a difference, but I am using PHP 8.0.

**Review by rosiel — APPROVED** [review]
Replicated the error, and this fixed it.

**Pull request merged**
