### PR TITLE
Mjordan issue 1521 redo

### PR DESCRIPTION
**Pull request by dannylamb**
**Github issues**: https://github.com/Islandora/documentation/issues/1549 and https://github.com/Islandora/documentation/issues/1550.

* Supersedes https://github.com/Islandora/islandora/pull/827

# What does this Pull Request do?

Accounts for the fact that @mjordan and @dannylamb are idiots. Specifically, this is a redo of the PRs https://github.com/Islandora/islandora/pull/778 and https://github.com/Islandora/islandora/pull/782, which Mark incorrectly opened against and were merged against the master branch.  Danny erroneously merged them :tada:

# What's new?

This PR improves https://github.com/Islandora/islandora/pull/827 by replacing calls to `Drupal::service` with dependency injection.

* Same things that were new in PRs https://github.com/Islandora/islandora/pull/778 and https://github.com/Islandora/islandora/pull/782:
    * Adds a new controller at `admin/reports/islandora/rdf_mappings` that generates and renders the report (including updating the menu links and routing YAML files as required)
    * Updates the `getUriFieldNamesForTerms()` function in the Islandora Utilities service

# How should this be tested?

1. Check out this branch. Within the `islandora` module directory:
   1. `git fetch origin`
   1. `git checkout mjordan-issue-1521-redo`
1. Clear your cache (`drush cr`)
1. Visit Admin > Reports > Field and term RDF mappings (refresh if you don't see this new item)
1. You should see the report listing fields and their RDF property mappings, and near the bottom, all taxonomies with terms that have external URIs / authority links. It's a long list.

# Additional Notes:

* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? Yes, but only adds more information to an existing report.
* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? Yes.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by mjordan** [comment]
@dannylamb should the testing instructions indicate my fork or the `mjordan-issue-1521-redo` branch within the Islandora repo?

**Comment by dannylamb** [comment]
Ah yeah, i just copy/pasta'd those instructions.  Let me see.

**Comment by dannylamb** [comment]
Yep, updated.

**Comment by elizoller** [comment]
I have a pretty vanilla d9 islandora playbook and i pulled in this PR, did a drush cr, and visited the report page. it appears to be loading things

Screen Shot 2021-04-28 at 9 04 14 AM

**Comment by elizoller** [comment]
I can confirm it showed multiple mappings where applicable and appeared to cover all of the various bundles

**Comment by elizoller** [comment]
Is there any concern about this report growing too large to load? i see that it includes all the taxonomy terms and I pulled this PR into my local of my institution's version of Islandora and it has some sample data in it and the report is VERY long. I'm wondering if it's just going to timeout in production where there is even more data.

**Comment by mjordan** [comment]
@elizoller good question. Would caching be a way to mitigate this? Maybe provide an option to seed this cache during Drupal cron runs? I'd be happy to work on that.

**Comment by mjordan** [comment]
@seth-shaw-unlv suggested adding a link to the new RDF namespace definitions form.

**Comment by dannylamb** [comment]
Maybe we could show a list of links that would take you to each individual table?  A little clunky, but then you're at least only rendering one table at a time.

**Comment by elizoller** [comment]
i would think it'd be ok for content types, but maybe each vocabulary should live on a separate page?

**Comment by dannylamb** [comment]
I'm happy to make a ticket for the suggested improvements.  Can we move this one along?

**Review by elizoller — APPROVED** [review]

**Comment by dannylamb** [comment]
Many thanks @elizoller

**Comment by dannylamb** [comment]
https://github.com/Islandora/documentation/issues/1813

**Pull request merged**
