### PR TITLE
Node and media delete action

### PR DESCRIPTION
**Pull request by ajstanley**
# What does this Pull Request do?

Provides an additional Action to delete a node along with all associated media and the files attached to those media.

# What's new?
Provides the Action in code, and an instantiation of that action in config

This is new functionality and should not have any effect on existing code.

# How should this be tested?
Once installed you should see a new action defined anywhere the Node Action Bulk Form is used (like the default content view)
image

# Documentation Status

No existing behaviour is affected, and AFAIK we allow all actions to be self-documenting.  It might be worth mentioning the 'no spaces in usernames if you want to delete Fedora files' somewhere

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/committers

### CODE REVIEW

**Comment by DonRichards** [comment]
I did test this last week on an existing isle-dc instance and it resulted in a white-screen. This might be a "user error" so I'm going to test again. I didn't test using the docs on [Testing a Pull Request](https://islandora.github.io/documentation/contributing/testing-a-pull-request/) so I'll follow those instructions and see if the method I was using to testing the PR was the problem.

**Comment by DonRichards** [comment]
Worked! Just adding notes on how I tested since there was an extra couple of steps not in the docs
```sh
composer config allow-plugins.cweagans/composer-patches true
composer require cweagans/composer-patches
curl -L https://github.com/Islandora/islandora/pull/1041.patch -o assets/pr-1041.patch
composer config extra.patches --merge --json '{"drupal/islandora": {"Node and media delete action: https://github.com/Islandora/islandora/pull/1041": "assets/pr-1041.patch"}}'
composer update drupal/islandora
chown -R nginx:  web/modules/contrib/islandora
drush config:export -y
cp web/modules/contrib/islandora/config/install/system.action.delete_node_and_media.yml config/sync/
chown -R nginx: config/sync/system.action.delete_node_and_media.yml
drush config:import -y
drush cr
```

**Review by DonRichards — DISMISSED** [review]

**Comment by adam-vessey** [comment]
If the new config is absolutely required for the functionality, there should probably be an update or post-update hook implemented to add it, which would also avoid shenanigans with having to copy configs around, as you could instead just run the update hooks.

**Comment by DonRichards** [comment]
Good call.

**Comment by ajstanley** [comment]
Update hook added

**Comment by DonRichards** [comment]
Testing this now.

**Comment by DonRichards** [comment]
Steps taken

```
composer config allow-plugins.cweagans/composer-patches true
composer require cweagans/composer-patches
curl -L https://github.com/Islandora/islandora/pull/1041.patch -o assets/pr-1041.patch
composer config extra.patches --merge --json '{"drupal/islandora": {"Node and media delete action: https://github.com/Islandora/islandora/pull/1041": "assets/pr-1041.patch"}}'
composer update drupal/islandora
chown -R nginx:  web/modules/contrib/islandora
drush updatedb
drush cr
```

**Review by DonRichards — APPROVED** [review]
Worked as expected.

**Pull request merged**
