### PR TITLE
STOMP message persistence

### PR DESCRIPTION
**Pull request by adam-vessey**
**JIRA Ticket**: N/A

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

Contains #839, slightly reworking and adding a fix for https://github.com/Islandora/documentation/issues/1857

# What does this Pull Request do?

Adds the header such that STOMP messages should be persistent.

# What's new?

Renamed the event handler method introduced in #839 to be less specific to auth, to add in the `persistent` header to be `true`, if it's not already set, allowing for the the case somebody ever desires things be persistent, such that they could implement a listener/subscriber and explicitly set it as `false`.

# How should this be tested?

Somewhat predicated on having ActiveMQ itself configured for persistence:
1. disable Karaf
1. trigger a derivative processed via Crayfish which is expected to succeed
1. restart Active MQ
1. enable Karaf

Without this PR, the message would be lost when restarting ActiveMQ.
With this PR, the message should be persisted to disk when ActiveMQ stops and loaded when it starts, and Karaf should receive and process the message accordingly.

The message persistence might also be verified via ActiveMQ's web ui.

# Additional Notes:

* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? Don't believe so.
* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? Unlikely.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by adam-vessey** [comment]
Rebased onto #839

**Comment by whikloj** [comment]
Hey @adam-vessey is there some configuration I need to do. 

Using a playbook installation and #839, I wanted to verify the failure first.

I take Karaf down, create a new Repository Item and add a Media to it (I used a Tiff). 

The Repository Item doesn't get persisted to Fedora and none of the derivatives generated. 

But when I bring Karaf back up they do start getting processed without the additional commit of this PR. Wondering if there is some setup I need. 

I had assumed that if ActiveMQ is running and you've defined a queue (and not a topic) then the message would wait around for a consumer. Which is what I am seeing.

**Comment by adam-vessey** [comment]
@whikloj: The messages would still be kept in memory by ActiveMQ, if it's not restarted... from what you've described, you've only done steps 1, 2, and 4; missing part 3 (which is where the persistence itself is actually tested).

**Comment by whikloj** [comment]
DOH 🤦

**Comment by whikloj** [comment]
Ok @adam-vessey I've tested this and it works. But I also merged #839 to have it go as its own commit. So when you get a chance to rebase this PR on main again I'll merge it. Thanks for all your work 🥇

**Comment by adam-vessey** [comment]
Rebased down to the one differing commit.

**Review by whikloj — APPROVED** [review]
👍

**Pull request merged**
