### PR TITLE
Fix typo in code comment.

### PR DESCRIPTION
**Pull request by kayakr**

### CODE REVIEW

**Comment by whikloj** [comment]
Hey @kayakr, could you complete an individual CLA. Unfortunately we can't accept PRs unless the foundation has one on file.
http://islandora.ca/resources/contributors
cheers

**Comment by willtp87** [comment]
@whikloj I think that has been handled https://github.com/Islandora/tuque/pull/151

**Comment by manez** [comment]
Thanks for the catch, @willtp87 . We do indeed have an iCLA on file.

**Comment by whikloj** [comment]
@willtp87 @manez @kayakr 
👍  all around.

**Pull request merged**
