### PR TITLE
#1534 Change config permission to 'administer site configuration'

### PR DESCRIPTION
**Pull request by kayakr**
**Github Ticket**:
#1534 Tighten access to Islandora IIIF config form 
https://github.com/Islandora/documentation/issues/1534

# What does this Pull Request do?

Changes config permission for Islandora IIIF config form from 'access administration pages' to 'administer site configuration' so that some roles can have (say) content administration via administration pages without being able to alter key site configuration.

A brief description of what the intended result of the PR will be and/or what problem it solves.

# What's new?
Changed permission for `/admin/config/islandora/iiif`

# How should this be tested?

With a user role with 'access administration pages' permission note that /admin/config/islandora/iiif is accessible. With this patch they should get "You are not authorised to access this page.", and 'administer site configuration' is required instead.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by manez** [comment]
This is probably me not understanding something simple, but I can't find the permission "access administration pages" to test this out. Is it the same as "Use the administration pages and help?"

**Comment by kayakr** [comment]
@manez That's the correct permission: "Use the administration pages and help" is the title used for the table row at `/admin/people/permissions` but `access administration pages` is the permission string used in code.

**Comment by DonRichards** [comment]
@kayakr to get a faster response to a PR it helps to make the "How to test" as approachable as possible. Something I find highly useful is to include step by step instructions with screen shots (if needed) to basically walk a noobie/newby through the process of seeing the original result, pull in the change, verify the change worked and any other thing they should check to approve the PR. I'd do this but I'm not completely sure what to test and I have a very limited time window of open time.

**Comment by manez** [comment]
Tested and it all seems to work as advertised. My user with "Use the administration pages and help" permissions could access  /admin/config/islandora/iiif before the PR, and can't afterwards.

**Comment by dannylamb** [comment]
Happy to merge based on your approval @manez

**Pull request merged**
