### PR TITLE
Change existence check to use islandora_object_load().

### PR DESCRIPTION
**Pull request by adam-vessey**
**Jira:** [ISLANDORA-1586](https://jira.duraspace.org/browse/ISLANDORA-1586) 

# What does this Pull Request do?

Simplify object existence check.

# How should this be tested?

Uninstall (not just disable) an installed solution pack module, and the message about [any installed objects from the given solution pack](https://github.com/adam-vessey/islandora/blob/7.x-ISLANDORA-1586/includes/solution_packs.inc#L487-L493) should be emitted.

# Additional Notes: 
* **Does this change require documentation to be updated?** No.
* **Does this change add any new dependencies?** No.
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No
* **Could this change impact execution of existing code?** Unlikely. 

**Tagging:** @jordandukart (as maintainer)

----
Adam Vessey
_Developer_
**[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content**

### CODE REVIEW

**Comment by jordandukart** [comment]
Don't see anything glaring in this, any other @Islandora/7-x-1-x-committers able to sign off on this?

**Comment by DiegoPino** [comment]
@adam-vessey, hi. 
I think this line is not needed anymore? (the $connection) at https://github.com/adam-vessey/islandora/blob/7.x-ISLANDORA-1586/includes/solution_packs.inc#L477. 

Also, just an edge case, but islandora_object_load does return something different than NULL or FALSE in case of tuque not being available. I don't think it's even possible to get to that stage without a running tuque, but just in case someone calls islandora_uninstall_solution_pack from a not UI triggered script? Could this be an issue? the filter will certainly fail.

Lastly, any performance issues of having a full object load versus just finding if the object is present?

Thanks!

**Comment by adam-vessey** [comment]
@DiegoPino 

1. True... Funnily enough, I don't think it was necessary before, with the API-A being available from the objects over which it's iterating... Anyway, [removed](https://github.com/Islandora/islandora/commit/763a7a8577bc328ec45a7bfffcecbaaa813caa76) (and also from the parallel "install" structure).
1. I'm unsure of what you are asking or stating here. [Looking at the code](https://github.com/Islandora/islandora/blob/b403953b2f0dd62b113ef7bf1919940a486657aa/islandora.module#L1215-L1253), it appears that `islandora_object_load()` should return `NULL` when Tuque itself is unavailable. Really, this is less of an issue with this pull request, since it was using the return of [`islandora_get_tuque_connection()`](https://github.com/Islandora/islandora/blob/b403953b2f0dd62b113ef7bf1919940a486657aa/islandora.module#L1183-L1213) blindly, which could have lead to attempting to access properties on `NULL`.
1. Unknown: Haven't dealt much with the `findObjects` endpoint at all (and the documentation regarding it makes me uncomfortable)... I suspect the `islandora_object_load()` might be slightly slower, but given that the code in question runs only during the uninstall of solution pack modules, I don't believe it should be an issue for the running of sites in general, and if it _is_, would want to look at rolling some other mechanism.

Thanks!

**Comment by DiegoPino** [comment]
Thanks @adam-vessey, yeah funny it was there in the first place, good to have this cleaned out. 
About 2. , i think i maybe misread the code but i was in the impression that, in case of `$tuque` "not being" there, the return was a drupal message generated here https://github.com/Islandora/islandora/blob/eaa4bc7838578b9a0ffb2761feffccb2fc3ed0c1/includes/tuque.inc#L110-L116. Anyway, not much impact. islandora Tuque would pop up with error before even getting there if absent.
3. Sounds fine, not that solution packs provide a big list of objects anyway.

Looks good to me.

**Comment by adam-vessey** [comment]
@DiegoPino 

About 2: I suspect if you dumped that backtrace in the method there, it's a result of [this call in `islandora_object_load()`](https://github.com/Islandora/islandora/blob/b403953b2f0dd62b113ef7bf1919940a486657aa/islandora.module#L1249), and immediately after, it [(explicitly) returns `NULL`](https://github.com/Islandora/islandora/blob/b403953b2f0dd62b113ef7bf1919940a486657aa/islandora.module#L1252)... It should still return `NULL` when that message is emitted.

**Comment by jordandukart** [comment]
This looks fine to me.

**Comment by DiegoPino** [comment]
:+1:

**Pull request merged**
