### PR TITLE
Document the add members and add media pages.

### PR DESCRIPTION
**Pull request by rosiel**
**GitHub Issue**: [Slack conversation](https://islandora.slack.com/archives/CM5PPAV28/p1658594240757819) with C.Z.:

"How can I add my own media types to add media? If I add them, they will not show up under add media"

# What does this Pull Request do?

Tells you, when on the "add Media" and "add Members" page, that the bundles below are available because they have the magic field configured to this bundle.

# What's new?

Help text on the Add Children (`/node/{node}/members/add`) and Add Media (`/node/{node}/media/add`) pages.

# How should this be tested?

* does the text show up?
* do you have suggestions to make it better? 

Note: I tried to get "this bundle" (the bundle of the current node) to show up as the bundle's human readable name, but without loading a bunch of extra classes I could only get it to show the machine name of the bundle. So I didn't. If you think it's worth it, please send code.

# Documentation Status

* Does this change existing behaviour that's currently documented? no. 
* Does this change require new pages or sections of documentation? no but new screenshots might be nice.
* Who does this need to be documented for? it _is_ documentation.
* Associated documentation pull request(s): ___  or documentation issue ___ see above.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties

### CODE REVIEW

**Comment by ysuarez** [comment]
Can you give me suggestions on how to test this with a clean ISLE instance? maybe just overwrite these files manually?src/Controller/ManageMediaController.php
src/Controller/ManageMembersController.php

**Comment by whikloj** [comment]
Hey @rosiel I'm finding the use of **this content type** a little confusing, but I don't have a great suggestion. Also I thought we should specify that `field_media_of` was a field, but maybe that is obvious.
> The available media types below have a *field_media_of* field and that field is configured to allow the current(?) content type.

Screen Shot 2022-09-12 at 11 31 40 AM

**Comment by rosiel** [comment]
I like that suggestion, thanks. I'll see what i can do.

**Comment by rosiel** [comment]
Ugh. A rebase error got into this branch. Sorry, I'll try again fresh.

**Pull request closed without merging**
