### PR TITLE
Chunking/byte-range datastream request race condition

### PR DESCRIPTION
**Pull request by adam-vessey**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1857

# What does this Pull Request do?

Closes up a race condition which could cause HTTP timeouts for datastream byte-range requests.

# What's new?

Introduces some file locking to ensure that the temporary files used in the byte-range response are not used before they are completely downloaded from Fedora. 

# How should this be tested?

Really, this should just get a regression test; make sure datastream byte-range requests still work.

If one want to try to see the present issue in action, firing up a pair of browser instances and attempting to play the same video with jwplayer may be able to produce the error, particularly with larger videos:

1. The first should load fine (if slowly, due to the large file)
2. The second, trying to load after the first was started while the first is still in progress (downloading the datastream to the temp directory), will likely see a shorter version of the file, and likely throw an error when hitting the end of the content it understands to be available.

With this pull request, this should no longer be possible... The second should now just wait until the file is complete, likely starting to play at approximately the same time as the first.

# Additional Notes:
* **Does this change require documentation to be updated?** No
* **Does this change add any new dependencies?** No.
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No
* **Could this change impact execution of existing code?** `islandora_view_datastream_retrieve_file_uri()` now may throw exceptions if it is unable to reliably grab datastream content.

At some point in the future, we may want to look at doing at conditionally piping through byte-range requests to Fedora, for those versions which support it... This could avoid the temp copies of files, possibly allowing the initial response to be delivered faster.

# Interested parties
@DiegoPino @willtp87

### CODE REVIEW

**Comment by jordandukart** [comment]
@Islandora/7-x-1-x-committers, @dannylamb

**Comment by dannylamb** [comment]
@whikloj @DiegoPino Is there any interest in checking this out, or do I need to step in and test?

**Comment by DiegoPino** [comment]
A few Questions:  

http://www.php.net/flock is an advisory lock, is it respected by drupal in general or should we not be worried about that?

Documentation suggests that the "Network File System (NFS), commonly used to provide file sharing across Unix boxes, is not suitable for use with flock()". Can be that a use case where this fails, and if so, how would that fail, moderate, badly, just same behaviour as before? 

Lastly, @jordandukart how do we test this?  Since it's a race condition it tries to solve, it's difficult to replicate. Any ideas on how to make sure this complicated mechanic solves the issue?

Thanks!

**Comment by whikloj** [comment]
@dannylamb I'll try to do this in the next couple days. I think I understood what @adam-vessey said at committer's a couple weeks back. Just keep getting buried.

**Comment by adam-vessey** [comment]
@whikloj @Islandora/7-x-1-x-committers, ping.

@DiegoPino As you indicate, it's an advisory lock, so only aware processes are expected to be affected... As these "chunk" files should only be touched by the given code, this is fine for our use, needing only to address a race condition in a relatively small bit of code.

To what documentation are you making reference? I'm not seeing it in the linked PHP man page (there are some mentions of NFS in comments, but nothing in the body of the document). I believe it would fail hard (as in, fail to obtain the lock and do nothing)... could possibly make it do best-effort, as it did before, but I could see this difficult-to-diagnose issue popping up again. 

Not sure if it's authoritative, but http://nfs.sourceforge.net/#faq_d10 indicates that NFS behaviour is implementation/version specific:

> The NFS client in 2.6.12 provides support for flock()/BSD locks on NFS files by emulating the BSD-style locks in terms of POSIX byte range locks. Other NFS clients that use the same emulation mechanism, or that use fcntl()/POSIX locks, will then see the same locks that the Linux NFS client sees.

**Comment by whikloj** [comment]
@adam-vessey sorry for the delay, testing this now.

**Comment by whikloj** [comment]
Ok I couldn't duplicate the error, I was trying manually and I think you would need a large file and slow data transfer from Fedora to catch the gap.

However I did not experience any issues playing my video as a result of this change.

The code is definitely more complex than before but it just seems to allow for checking that the file previously tested by `file_exists` is the complete contents of the datastream and not a partially downloaded one. 

Also huge 👏  to @adam-vessey for the great documentation inside the function and it

So @dannylamb and @DiegoPino if one of you wants to try and force the race condition, I'll leave it to you.

I'm okay with this.

**Comment by DiegoPino** [comment]
@whikloj can't reproduce the condition that originated this pull, but since you tested and you found it as fast as before, I'm ok and would appreciate you merging. 

@adam-vessey, regarding NFS issues and PHP locks, true, it's not in the main function description which is also uncomplete according to other users,  but the issue is reported in many places  including published and printed books, forums, even GitHub issues. https://www.google.com/search?client=safari&rls=en&q=flock()+NFS&ie=UTF-8&oe=UTF-8#q=flock()+NFS+php
yields enough

That said, really, I don't have an use case for mounting drupal's temp or any other part of its filesystem via NFS, so if this pull does not make drupal/islandora slow and does not break anything I'm ok with it.

**Pull request merged**
