### PR TITLE
Use continue 2 in switch inside for loop (for php 7.3)

### PR DESCRIPTION
**Pull request by dannylamb**
**Github Issue** Resolves https://github.com/Islandora/documentation/issues/1466

# What does this Pull Request do?

Uses `continue 2` in `LinkHeaderSubscriber` since we've got a `switch` in a `foreach`. It's for PHP 7.3 compatibility.

# How should this be tested?

* Travis's 7.3 tests shouldn't error on this anymore

OR

* Use isle-dc and `make dev`
* `docker exec -it isle-dc_drupal_1 drush cr`
    * You should see the warning about using `continue 2`
* `cd` into your codebase folder and pull this PR into your `islandora` module
* `docker exec -it isle-dc_drupal_1 drush cr`
  * You should _not_ see the warning about `continue 2`

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Review by seth-shaw-unlv — APPROVED** [review]
👍

Just waiting for Travis to come back green.

**Comment by nigelgbanks** [comment]
> Just waiting for Travis to come back green.

Don't think Travis is passing on any branches this seems safe enough to push through.

**Comment by seth-shaw-unlv** [comment]
Yeah, some time ago you simply needed to keep retrying until it came back... but I think we've hit bigger issues.

So, I tried to run the tests on Isle and it is returning this error:
```
Class 'PHPUnit\Framework\TestCase' not found in include() (line 40 of /var/www/drupal/web/core/tests/Drupal/Tests/BrowserTestBase.php)
```

**Comment by rosiel** [comment]
I'm [testing this out](https://travis-ci.org/github/rosiel/islandora/builds/737738258) along with @whikloj 's 'fix-travis'  branch. Since his fixes [seemed promising for php 7.2,](https://travis-ci.org/github/rosiel/islandora/builds/737731960) i'm hopeful.

**Review by whikloj — APPROVED** [review]
Sorry I've been a little sidetracked. I think this is fine to go in with or without Travis's blessing.

**Comment by whikloj** [comment]
But I will continue to work on the PHPUnit test breakout, maybe @rosiel or I can crack this code.

**Comment by seth-shaw-unlv** [comment]
I think we have enough consensus to merge w/o Travis.

**Pull request merged**
