### PR TITLE
Less gemini

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Part of this mess: https://github.com/Islandora-Devops/isle-dc/pull/132

Goes wtih https://github.com/Islandora/islandora_defaults/pull/53

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?

Removes some actions that we no longer need since we've dropped Gemini.

# What's new?

Does this warrant an update hook to delete it from existing sites?  Or should I just add instructions to do it in the release notes? @Islandora/8-x-committers ?

### CODE REVIEW

**Comment by dannylamb** [comment]
Linking this to https://github.com/Islandora/documentation/issues/1848 since that's how I discovered that this needs to be deleted.

**Comment by whikloj** [comment]
I'd vote for an update hook if it's not too complicated to write.

**Comment by dannylamb** [comment]
done

**Review by elizoller — APPROVED** [review]
i pulled in this PR, verified the actions were deleted. tested adding an item with an original file and verified that the original file still made it to fedora. seems good.

**Comment by dannylamb** [comment]
can haz merge?

**Pull request merged**
