### PR TITLE
Update IslandoraFunctionalTestBase.php

### PR DESCRIPTION
**Pull request by dannylamb**
**Github Issue**: Discovered on https://github.com/Islandora/islandora/pull/797

# What does this Pull Request do?

Fixes tests so Travis passes.

# What's new?

Manually enabling `menu_link_content` in our Functional tests. 

# How should this be tested?

Travis should be appeased

# Additional Notes:

Dunno why this popped on us now :man_shrugging: 

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Travis, travis, travis.... haven't we gone through this time out business before??

**Comment by dannylamb** [comment]
Ugh... we're literally at the point where we'll need to refactor just to put the tests in other repos so we can survive Travis's timeout limits....  Not entirely sure how best to proceed at this point.

**Comment by rosiel** [comment]
Can we discuss/work on this at the Oct 14 Tech Call?

**Comment by dannylamb** [comment]
Yes please.  Feel free to add it to the agenda: https://github.com/Islandora/documentation/wiki/October-14%2C-2020

**Comment by rosiel** [comment]
Done with #805

**Pull request closed without merging**
