### PR TITLE
Revert "Dummy composer.json to see if it'll appease packagist"

### PR DESCRIPTION
**Pull request by whikloj**
Reverts Islandora/islandora#734

Because I should have waited the 24 hours. 

@DiegoPino if this is okay, you can merge it in 24 hours.

### CODE REVIEW

**Comment by DiegoPino** [comment]
Thanks for addressing my question. But it was a question really about the workflow and how the unifying repositories applies to committers. I guess we will have time to talk about this. Thanks again

**Comment by DiegoPino** [comment]
@whikloj for some reason i lost my Travis privileges and can not restart the failed test. You ok with me merging on Red status?

**Review by DiegoPino — APPROVED** [review]
But travis is failing i can not restart it using my 7.x powers

**Comment by whikloj** [comment]
@DiegoPino I had to select the actual job and use the "Restart job" button on the logging page because I couldn't see any buttons either. Once I restarted it then I could see all the other restart buttons. 🤷‍♂

**Pull request merged**
