### PR TITLE
Fedora url

### PR DESCRIPTION
**Pull request by Natkeeran**
** Please hold on from testing.  Will provide more info. **

**GitHub Issue**: (link)
Part of the work towards: https://github.com/Islandora/documentation/issues/926

### CODE REVIEW

**Comment by bradspry** [comment]
This is a fantastic integration on multiple levels!  Thank You for your total grasp of Drupal multi-site and settings.php! 💯

**Comment by dannylamb** [comment]
Travis is going to continue to fail until https://github.com/Islandora/islandora/pull/747 gets merged, but I've tested this with all the other PRs for https://github.com/Islandora/Alpaca/pull/65 and it's all good.  I'm happy moving forward, as this has nothing to do with why tests are failing.

**Comment by elizoller** [comment]
does this mean you can just modify the flysystem block in the settings.php to accomodate a new root?
like 
```$settings['flysystem'] = [
  'fedora' => [
    'driver' => 'fedora',
    'config' => [
      'root' => 'http://127.0.0.1:8080/fcrepo/rest/',
    ],
  ],
];
```
could become
```
$settings['flysystem'] = [
  'fedora' => [
    'driver' => 'fedora',
    'config' => [
      'root' => 'http://127.0.0.1:8080/fcrepo/rest/mynewroot/',
    ],
  ],
];
```

**Comment by dannylamb** [comment]
Yes, although we may still have to smooth out islandora-playbook to make sure everything deploys properly if you build a new box.

**Pull request merged**
