### PR TITLE
Test on PHP 8.3 and Drupal 10.3

### PR DESCRIPTION
**Pull request by rosiel**
**GitHub Issue**: (link)

* Other Relevant Links (Google Groups discussion, related pull requests,
 Release pull requests, etc.)
* Slack convo: https://islandora.slack.com/archives/C04DBSD9J4F/p1709825383171759

# What does this Pull Request do?

Tests now run on PHP 8.1, 8.2, and 8.3 and Drupal 10.1, 10.2, and 10.3-dev.

# What's new?

* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)?  no
* Could this change impact execution of existing code? no

# How should this be tested?

* Tests should pass.

# Documentation Status

* Does this change existing behaviour that's currently documented? no
* Does this change require new pages or sections of documentation? no
* Who does this need to be documented for? no
* Associated documentation pull request(s): ___  or documentation issue ___

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/committers

### CODE REVIEW

**Comment by rosiel** [comment]
I could use some help here. I "fixed"(?) all the tests so that they don't use `$this->t()` anymore (this seems to have been a best practice that has now been changed?) but they are still failing, and I do not have the setup to diagnose this:

```
Testing 
.................E........                                        26 / 26 (100%)

Time: 25:02.194, Memory: 16.00 MB

There was 1 error:

1) Drupal\Tests\islandora\Functional\LinkHeaderTest::testMediaLinkHeaders
TypeError: Behat\Mink\Session::setRequestHeader(): Argument #1 ($name) must be of type string, int given, called in /opt/drupal/web/core/tests/Drupal/Tests/UiHelperTrait.php on line 235

/opt/drupal/vendor/behat/mink/src/Session.php:199
/opt/drupal/web/core/tests/Drupal/Tests/UiHelperTrait.php:235
/home/runner/work/islandora/islandora/build_dir/tests/src/Functional/LinkHeaderTest.php:145
/opt/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:728
```

**Comment by alxp** [comment]
I think I can run these tests fro ma local homebrew PHP8.3 setup. I know there a re a few PHPUnit tests that assume the existence of an ActiveMQ server but I should be able to get to the problem you're seeing. Will report back.

**Comment by adam-vessey** [comment]
Checking out the line in question from the test: https://github.com/Islandora/islandora/blob/3065c87874b7da0440fff494d0e51c938b855fd7/tests/src/Functional/LinkHeaderTest.php#L145 and comparing against [the documentation for the method](https://api.drupal.org/api/drupal/core%21tests%21Drupal%21Tests%21UiHelperTrait.php/function/UiHelperTrait%3A%3AdrupalGet/9), looks like it expects things as key/value, not a numbered/sequential array, so it should maybe instead be:

```php
$this->drupalGet($media_url, [], ['Cache-Control' => 'no-cache']);
```

As in, I'm thinking it's trying to use the numerical offset as the `$name` of a header (which should be a string, as so causing the error). 

There may be some other sections requiring a similar fix, such as https://github.com/Islandora/islandora/blob/3065c87874b7da0440fff494d0e51c938b855fd7/tests/src/Functional/LinkHeaderTest.php#L177

**Comment by aOelschlager** [comment]
@alxp You should be able to test this now with the tag issue-329. Nigel updated those images to use PHP 8.3.

**Review by alxp — APPROVED** [review]
All changes look good.

**Pull request merged**
