### PR TITLE
coder_fixes

### PR DESCRIPTION
**Pull request by ajstanley**
**Issue**: (https://github.com/Islandora/documentation/issues/1620)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?

A few coder changes to keep Travis happy.

# What's new?
Mostly adding Class descriptors and breaking up inline arrays.

# How should this be tested?
Everything should still work - no logic was changed anywhere.  Travis Coder ought to pass if it's configured to ignore MDs

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Oddly, travis failed because the `menu_link_content` appeared to be missing. I don't know if this dependency was implied before (through the wonderful chain of module dependencies) but now disconnected (maybe we should add it as a test dependency in `islandora.info.yml` just to be explicit) or if it is simply Travis gremlins. Nothing in the PR would have dropped it. I've restarted the build just in case it was a fluke. 

If it fails, someone with more Travis chops than we will probably have to look into this; or we could have @ajstanley add it to the info file and see if that fixes it.

Tagging @dannylamb.

**Comment by dannylamb** [comment]
Yeah... nothing here is messing with any of that...  I can dig this afternoon :mechanic:

**Comment by dannylamb** [comment]
Having a heck of a time getting tests to run on ISLE... I'm hopping over to a vagrant instance and will try there.

**Comment by dannylamb** [comment]
Ok, I just confirmed this problem exists on fresh install without the multi-file media changes.  So it's got nothing to do with what you did @ajstanley.  I'll dig a bit longer but these changes are good in my opinion. `phpcs` is passing.

**Comment by dannylamb** [comment]
So... both `token` and `context` use `menu_link_content`, which is a core module.  Maybe I just need to manually enable it in the functional tests?

**Comment by dannylamb** [comment]
So I got it working with manually enabled `menu_link_content` in `IslandoraFunctionalTestBase`.  I'm still playing around with it, like maybe I need to be enabling `token` or `menu_ui` instead.  But nonetheless... we can fix this.  Incoming PR.

**Comment by dannylamb** [comment]
Actually, I'll merge this in first and you can test with the forthcoming PR.  Just realizing Travis won't pass on either of these unless one comes in first.

**Review by dannylamb — APPROVED** [review]
These are all good changes.  Travis failures are unrelated to this code (or any other recently committed code for that matter).

**Pull request merged**
