### PR TITLE
Make rdf namespaces configurable (Issue 1520)

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1520

Supersedes https://github.com/Islandora-CLAW/islandora/pull/78

# What does this Pull Request do?

Takes the hard-coded namespaces in islandora.module and instead loads them from configuration.

# What's new?

* Moved namespaces from islandora.module into islandora.settings.yml
* Updated islandora.module to pull namespaces from config instead of being hardcoded
* Updated schema to add rdf_namespaces
* Updated islandora core settings form to update rdf_namespaces config

# How should this be tested?

* Create some records and make sure the JSON-LD looks fine
* Apply the PR
* Run drupal updates (`drush updb -y`)
* Clear cache
* Make sure the JSON-LD looks the same
* Go to the core settings form ('/admin/config/islandora/core') and change one of the namespaces used in the JSON-LD you tested.
* Clear cache again
* View the JSON-LD and see the modified namespace in use.

# Additional Notes:

Namespaces hardcoded by other modules in their namespace hooks may or may not be overridden by your values in this config. It depends on the processing order of your modules, which can be changed. The [Drupal 7 docs on this topic](https://www.drupal.org/docs/7/creating-custom-modules/howtos/how-to-update-a-modules-weight) still apply.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by elizoller** [comment]
i'm getting a whitescreen of death with apache error in my local install and i'm realizing its because i have the rdf_namespaces hook that specifies rdua. so that might answer your question about what happens on a collision
```
[Wed Apr 21 17:52:50.404120 2021] [php7:notice] [pid 24171] [client 10.0.2.2:58998] Uncaught PHP Exception Exception: "Tried to map 'rdau' to 'http://rdaregistry.info/Elements/u/', but 'rdau' is already mapped to 'http://www.rdaregistry.info/Elements/u#'." at /var/www/html/drupal/web/core/modules/rdf/rdf.module line 120
```

**Comment by mjordan** [comment]
Since #827 provides a report of current namespaces, it would be useful to provide a link from that report to the admin form this PR introduces.

**Comment by seth-shaw-unlv** [comment]
@mjordan, with the new PRs, #827 should link the JSON-LD form instead: `Url::fromRoute('system.jsonld_settings')`.

**Comment by seth-shaw-unlv** [comment]
Superseded by #832

**Pull request closed without merging**
