### PR TITLE
Issue 2100 remove override facets js

### PR DESCRIPTION
**Pull request by wgilling**
**GitHub Issue**: (link)
https://github.com/Islandora/documentation/issues/2100

* Other Relevant Links (Google Groups discussion, related pull requests,
 Release pull requests, etc.)

# What does this Pull Request do?
This removes the override javascript that was causing problems executing the soft-limits.js code from the core facets module to address https://github.com/Islandora/documentation/issues/2100 

A brief description of what the intended result of the PR will be and/or what problem it solves.
the javascript libraries are no longer overridden - using the core facets/js/soft-limits and views-ajax javascript works as expected.

# How should this be tested?
To test, perform a search on a site that will give you at least 3 different facet values for a facet that uses a "List of links" configuration and has a value set for "Soft limit" ( The description for this "Limit the number of displayed facets via JavaScript." ) to limit facets at 3. 

When the code works correctly, there should be no console errors relating to that soft-limits.js. Also, the facet that was limited will now only display the top 3 facet values and a link to "Show more".

### CODE REVIEW

**Comment by jordandukart** [comment]
@wgilling believe there's an intended commit/change in here in regards to `islandora_iiif` if you want to re-roll this.

**Comment by wgilling** [comment]
yes -- I do not know how that "test" commit is even in there, but I will update the feature branch when I have time.

**Comment by simonhm** [comment]
Hi @wgilling 
Installing the patch fails because the code that it is trying to patch has changed since the patch was last updated (May 2022).

Here is the output from the command executed in the directory:

`.../var/www/html/drupal/web/modules/contrib/islandora$
curl https://patch-diff.githubusercontent.com/raw/Islandora/islandora/pull/870.patch | git apply -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14529    0 14529    0     0  48269      0 --:--:-- --:--:-- --:--:-- 48269
Checking patch modules/islandora_iiif/src/Plugin/views/style/IIIFManifest.php...
error: while searching for:

namespace Drupal\islandora_iiif\Plugin\views\style;

use Drupal\views\Plugin\views\style\StylePluginBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Messenger\MessengerInterface;

error: patch failed: modules/islandora_iiif/src/Plugin/views/style/IIIFManifest.php:2
error: modules/islandora_iiif/src/Plugin/views/style/IIIFManifest.php: patch does not apply
Checking patch modules/islandora_advanced_search/islandora_advanced_search.module...
Checking patch modules/islandora_advanced_search/js/facets/facets-views-ajax.js...
Checking patch modules/islandora_advanced_search/js/facets/soft-limit.js...`

It looks like there needs to be some additional development and testing done.
Simon.

**Comment by wgilling** [comment]
closing this - https://github.com/Islandora/islandora/pull/926 replaces it (without any merge conflicts)

**Pull request closed without merging**
