### PR TITLE
Switch to using PHPUnit directly and splitting into testsuites.

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: n/a

# What does this Pull Request do?

Switches up our travis testing to use PHPUnit directly instead of the Drupal `run-tests` script. This allows us to define testsuites and break up the actual testing into smaller chunks.

It also disables xdebug as we are not tracking code coverage in the Drupal modules so this should make it a little faster.

# What's new?
A new custom `phpunit.xml` which is copied to Drupal root and then PHPUnit is run calling one of the "testsuite" names defined inside.

# How should this be tested?

Travis will be 
Super green

# Interested parties
@Islandora/7-x-1-x-committers specifically @rosiel and @dannylamb

### CODE REVIEW

**Comment by whikloj** [comment]
Also wondering if there is a reason this repo is still using `travis-ci.org` and not `travis-ci.com`?

**Review by rosiel — APPROVED** [review]
@whikloj great stuff!!

**Comment by rosiel** [comment]
Bam! Question still stands... .org vs .com?

**Comment by dannylamb** [comment]
Yes... there was a reason it's not on `.com`, but it's been a minute. I think it might have had something to do with requiring I change the master branch or something?  I'd honestly have to dig for a bit.

Also, noticed that PR removed codecov.  Is it possible to add that back in or do we have to compromise and give up codecov to use this approach? I'm not :100:  on how it would all play out if you tried to turn it back on.

**Comment by whikloj** [comment]
For the record, enabling XDebug **triples** each individual run time for those tests that don't then run out of time. Even using the (apparently) faster `phpdbg` available in PHP versions >= 7.0.

**Comment by whikloj** [comment]
For comparison, no code coverage testing
https://travis-ci.com/github/whikloj/islandora/builds/191563024

With `phpdbg` code coverage
https://travis-ci.com/github/whikloj/islandora/builds/191712232

**Pull request merged**
