### PR TITLE
Update testing

### PR DESCRIPTION
**Pull request by whikloj**
**GitHub Issue**: n/a

# What does this Pull Request do?

Updates the testing matrix to pull the current minor version instead of locking.

This will test:
1. Drupal 9.3.x, 9.4.x on PHP 7.3 and 7.4
2. Drupal 9.3.x, 9.4.x on PHP 8.0 and 8.1.
3. Drupal 10.0.x on PHP 8.0 and 8.1 (D10 doesn't support 7.3/7.4)

Only number 1 above is required to pass, the others can fail.

# How should this be tested?

Changes testing matrix

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/8-x-committers

### CODE REVIEW

**Comment by whikloj** [comment]
Because I changed the way the test runs are named, the expected tests are run but named differently. We'll need someone with access to change the required status checks if this is to be merged.

**Comment by seth-shaw-unlv** [comment]
@whikloj, I think I have the necessary permissions. Can you be more specific about what I need to update?

**Comment by whikloj** [comment]
@seth-shaw-unlv Settings -> Branches -> Branch Protection Rules (for 2.x) -> Edit -> Protect matching branches 

Here you want to remove the old checks and then ✅ off the rules we want to require for PRs.

**Comment by seth-shaw-unlv** [comment]
Branch protections have been updated.

**Review by seth-shaw-unlv — APPROVED** [review]
👍

**Pull request merged**
