### PR TITLE
Move rdf namespaces into jsonld config (Issue-1520)

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1520

Supersedes https://github.com/Islandora/islandora/pull/831

# What does this Pull Request do?

Enables adding RDF namespaces in config.

# What's new?

* Removes hook_rdf_namespaces
* Adds install and update hooks to add the previously hard-coded namespaces into the jsonld.settings config

# How should this be tested?

Test in conjunction with https://github.com/Islandora/jsonld/pull/53.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Note: we will need to merge the JSON-LD PR before Travis is calmed.

**Comment by dannylamb** [comment]
Restarting tests now that https://github.com/Islandora/jsonld/pull/53 has been merged.

**Comment by seth-shaw-unlv** [comment]
@dannylamb, green means go!

**Review by dannylamb — APPROVED** [review]
Yessir :rocket:

Tested with https://github.com/Islandora/jsonld/pull/53 during the open meeting.  Good stuff.

**Pull request merged**
