### PR TITLE
Removing jenkins and doxygen stuff

### PR DESCRIPTION
**Pull request by dannylamb**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2155

# What does this Pull Request do?

Deletes Jenkins and Doxygen files.

# How should this be tested?

If Travis abides, we're good.

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@dannylambI guess this is one of those 24 hours exceptions right? nothing will break and nobody will oppose.  Let me know to merge, merge. 😁

**Comment by dannylamb** [comment]
@DiegoPino I guess?  If folks are ok with this, I'll have to replicate it across _all_ our modules 😓

**Comment by dannylamb** [comment]
Haha, uh oh  Travis is displeased.  Looks like we still actually use the build.xml antfile?!?!?!

Let me see what I can do.

**Comment by DiegoPino** [comment]
@dannylamb it is here
https://github.com/Islandora/islandora/blob/7.x/.travis.yml#L48

**Comment by DiegoPino** [comment]
And yes 😢 its all over the place in every module :sneezing_face:

**Comment by mjordan** [comment]
If making this happen is straight foward, perhaps each component manager could do it to their respective modules?

**Comment by DiegoPino** [comment]
@mjordan I support that idea. Time to give Component Managers something to care for :egg: Will do my part this week.  thanks

**Comment by dannylamb** [comment]
Ooops, that's not right.  I'm scanning the wrong directory.

**Comment by dannylamb** [comment]
Ok, I think I got it.  We'll see once Travis stop churning on it.

**Comment by jonathangreen** [comment]
I wonder if we're going to do a big travis fest again, if we want to try making our travis files a little simpler and more centrally managed. We could probably write a shell script that replaces [this part](https://github.com/dannylamb/CLAW/blob/0550f6cfae755d7460a9eb2150c7b30a0aa240d5/.travis.yml#L48-L52) of every `.travis.yml` file and grab is from the Islandora repo. Taking a cue from the Ansible testing we are doing in CLAW. Don't want to overcomplicate this effort... so just ignore if its too much work.

**Comment by dannylamb** [comment]
@jonathangreen I can try and set that up

**Comment by dannylamb** [comment]
We call tests by feeding in the module name, and sometimes have embedded test modules and other unexpected stuff, so I can't really consistently execute tests across all modules.  But I can do all the other checks, which I just pushed changes for.  We'll see how it goes.

**Comment by dannylamb** [comment]
Meh, I ended up wrapping the test call function as well, just so we don't have to make a bajillion changes if we end up changing ports or anything like that.

**Comment by dannylamb** [comment]
:wave: :game_die:

**Comment by dannylamb** [comment]
...and :snake: :eyes:  Let's roll 'em again: :wave: :game_die:

**Comment by rosiel** [comment]
Boom! Now all that's left is every other module 😜

**Pull request merged**
