### PR TITLE
Fix multi-file media to allow image fields only on image derivatives.

### PR DESCRIPTION
**Pull request by rosiel**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/2003

# What does this Pull Request do?

with @ajstanley, fixes the general and the image case of multifile media derivatives so that expected behaviours are maintained.

# What's new?

* reverts #860 which allowed _all_ multifile media derivatives to have file or image fields,
* new behaviour (was the current behaviour until #860) is that by default, multi-file media derivatives must point to file fields. 
* changes the "Image derivative for media attachment" to allow image fields instead of file fields.

This change is set in the UI form and can probably be overridden by setting up the action in the raw config, if you so desire. 

* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)?  no
* Could this change impact execution of existing code? no

# How should this be tested?

Reproduce
* on 2.x-dev, enable Islandora and Islandora Image.
* Go to Configuration > System > Actions and set up a new "Generate a derivative file for media attachment". 
* You should be able to select any image or file fields you have enabled (including the defaults like `field_media_file` and `field_media_image`.). The fact that you can see images is unnecessary.
* Set up a "Generate an image derivative for media attachment". 
* You should be able to select any image or file field. The fact that you can select file fields is unnecessary.

Test fix
* With this PR, "Generate a derivative file for media attachment" should only allow file fields.
* With this PR, "Generate an image derivative for media attachment"
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

# Documentation Status

* Does this change existing behaviour that's currently documented? i don't think this is documented
* Does this change require new pages or sections of documentation? 
* Who does this need to be documented for? everybody
* Associated documentation pull request(s): ___  or documentation issue  : https://github.com/Islandora/documentation/issues/2140

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties
@Islandora/committers

### CODE REVIEW

**Comment by whikloj** [comment]
@rosiel I'm a little confused on how the weird images that Drupal considers files get handled with this change to the "Generate Image Derivative For Media Attachement". If I wanted to create a JP2 can that go in an image field, and if I want to generate a Tiff from (say) a PDF so I use the "Generate File Derivative..." instead?

Otherwise this seems to work as described and reduces the available fields.

**Comment by rosiel** [comment]
I'll look this over in more detail. I think you may be right that if you want to create a JP2 derivative from a TIFF you might unintuitively need to use the "File derivative" option.

**Comment by nigelgbanks** [comment]
In the default site configuration (_I'm testing against the starter site_) `field_media_file` seems to be set up to handle `tiff, tif, jp2` whereas `field_media_image` is set up to only handle `png, gif, jpg, jpeg`. 

With this change, I'm no longer able to select `field_media_file` for `generate_an_image_derivative_for_media_attachment` actions, which is the intention, but likely the defaults should change such that `field_media_file` no longer handles `tiff, tif, jp2` and `field_media_image` can handle them? 

I'm uncertain if this will cause issues, as `tiff` and `jp2` images cannot be displayed in the browser without a IIIF viewer. Does Drupal make some assumptions about image fields? Perhaps that why this is set up in this way?

I tried to manually change the `field_media_image` to also have `tiff` and `jp2`, though this doesn't seem to be reflected in the wiget.

**Field Settings**
Screenshot 2022-12-14 at 12 17 05

**Create Image Media form**
Screenshot 2022-12-14 at 12 17 37

Though that being said, the `generate_image_derivative_file` is not used in the starter site, only `generate_image_derivative` is which works with the `field_media_file`. So, there is no problem here other than my confusion as to how this all works :D

**Review by nigelgbanks — APPROVED** [review]
Works as stated, I was able to add another image field onto my image media type and populated it via the new action, which was limited to only selecting image fields.

**Comment by rosiel** [comment]
Thank you! We should document the multifile media better so that you know that if you're creating a tiff or jpeg, you need to use File. 

Drupal _does_ make assumptions about images. To my knowledge, Drupal Image fields refuse to accept JP2 or Tiff. I think this has something to do with the Drupal ImageService interface (which i understand is a wrapper for some backend software like imagemagick or GD). The ImageService perhaps outlaws those file types? or perhaps if we had a version of imagemagick that was compiled properly it would work? But would we want to ship drupal software that makes those kinds of assumptions about the capabilities of underlying and abstracted services?)

**Pull request merged**
