### PR TITLE
Some datastream improvements.

### PR DESCRIPTION
**Pull request by willtp87**

### CODE REVIEW

**Comment by willtp87** [comment]
https://jira.duraspace.org/browse/ISLANDORA-1366

**Comment by willtp87** [comment]
@ruebot

This pull addresses an instance of the issue identified in https://jira.duraspace.org/browse/ISLANDORA-1366

As component manager, do you mind reviewing this change?

Thanks,
William Panting

**Comment by willtp87** [comment]
@ruebot

My testing was through the required objects page. Having both tested is good. You may want to double check it that way as well. I think this is good to go.

Thanks,
William Panting

**Comment by willtp87** [comment]
@ruebot

I think we can safely merge.

Thanks,
William Panting

**Comment by DiegoPino** [comment]
Hi @willtp87. In another chapter or `text/xml` versus `application/xml` i was searching in stack's  source code if we had other text/xml that could affect a change @rosie pulled for xml_forms, and i found out that at the solution packs objects check in Islandora, there was a check agains `text/xml`, here:

https://github.com/Islandora/islandora/blob/f6314d5a6189a9bdbc902535c72ab2ba2ef39306/includes/solution_packs.inc#L542-L544

I was thinking maybe, since we are moving to `application/xml`, and in particular for this change, all `application/xml` datastreams would be ignored by that piece of code, but i'm not sure. Are you aware during your tests of any problem when checking for out of date date streams? 

Thanks!

**Comment by willtp87** [comment]
@DiegoPino

I did not see any issue but I'll look into it.

Thanks!

----
William Panting
_Developer_
*[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content*

**Comment by willtp87** [comment]
@DiegoPino

I don't think this piece of code is necessary and we don't rely on it.
I think it is a piece of cruft left over from before we [started comparing the complete XML](https://github.com/Islandora/islandora/commit/d0de6d6b9096fe57162a5846d6902383e1577979).
It should probably be removed. I think we left it in because we were unsure at the time if we could keep using the more expensive process.

Thanks!

----
William Panting
_Developer_
*[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content*

**Comment by DiegoPino** [comment]
@willtp87, perfect. Thanks a lot for looking at it.

**Pull request merged**
