### PR TITLE
ISLANDORA-1998 Check correct permission for replace ds link.

### PR DESCRIPTION
**Pull request by rosiel**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1998

* Discussion in Islandora Mailing List: https://groups.google.com/forum/#!topic/islandora/E0q3e-ZiK7Q 

# What does this Pull Request do?

Checks the right permission when deciding whether to show "Replace" datastream link.

# What's new?

ISLANDORA_REPLACE_DATASTREAM_CONTENT

# How should this be tested?

A description of what steps someone could take to:
* Give a user permission to replace datastreams, but not to view datastream history.
* Before this PR: That user can't replace datastreams in [object]/manage/datastreams.
* After this PR: That user sees the 'Replace' links and can replace a datastream.

# Interested parties
@jordandukart or @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@rosiel thanks! and a few things here. I need to update Travis to Drupal 7.55 to avoid all PHP 7.x tests to fail (and i need time!) and i wanted to check with you (in specific to this pull) if after the change a user that has permissions (explicitly set ) to see Datastream history, which previously meant in fact it had permission to replace a datastream, will now be not be able to do so? I feel since this is a bug, if that was the case then it was wrong, but maybe some people depend on this and have 1000x users already configured like that? @jordandukart any thoughts on this also?

**Comment by jordandukart** [comment]
I mean I imagine that'd be a possible edge case @DiegoPino?

**Comment by DiegoPino** [comment]
@jordandukart @rosiel I'm ok with assuming that that "edge case" is just a misunderstanding based on this Bug and we can move on with this pull if you all are Ok with that. Probably a release note (7.x-1.10) and leveraging the Bug from "minor" to something more red-ish could help.  According to our travis setup file we are getting always the latest drupal release, and 7.55 is planned for tomorrow
https://groups.drupal.org/node/516891
Should we wait? Or are you Ok with going on with failing travis?

**Comment by DiegoPino** [comment]
@rosiel @jordandukart mmm.. wait. Not sure about the edge case: Ok, right now a user that has access to ISLANDORA_VIEW_DATASTREAM_HISTORY can revert to a previous  version and replace when dealing with versions... which is in fact a datastream replacement.. right? Should define some consistency there. Because this changes what to expect.
https://github.com/Islandora/islandora/blob/dae68a3678272674ecba502e78b8a8c62c6d3ba0/islandora.module#L305-L313 Allows anyone with ISLANDORA_VIEW_DATASTREAM_HISTORY to replace and revert.

**Comment by jordandukart** [comment]
Okay by me seeing we can re-run builds after the fact.

**Comment by rosiel** [comment]
@DiegoPino to clarify your edge case, this is about the "replace" link in the Manage>Datastream table. The  previous setup checked both ISLANDORA_REPLACE_DATASTREAM_CONTENT and ISLANDORA_VIEW_DATASTREAM_HISTORY. They would not actually have seen the "replace" link unless they had both permissions in place. 

As for the other thing, i.e. if you go into view datastream history, does this affect whether you can re-instate a previous version? That's a separate permission, ISLANDORA_REVERT_DATASTREAM, which as far as I can tell can be granted independently from REPLACE_DATASTREAM_CONTENT.  

The line where it checks the "REVERT" permission: https://github.com/Islandora/islandora/blob/dae68a3678272674ecba502e78b8a8c62c6d3ba0/islandora.module#L335-L344

**Comment by DiegoPino** [comment]
@rosiel you are right!
 I got confused because [function islandora_datastream_version_table](https://github.com/Islandora/islandora/blob/847f3dac6bdeb439a5d92b2c625826e8597bed89/includes/datastream.version.inc#L68-L85) renders the replace and revert links anyway when looking at the versions (when you have view datastream history thingy).. even if you don't have the permissions. 

So ok, all cool

**Comment by DiegoPino** [comment]
@rosiel thanks for keeping just one check. helps with consistency. Once Travis finishes (failing) will marge

**Comment by rosiel** [comment]
OK, after discussing with Diego, I removed the check entirely from the function that builds the table (template_preprocess_islandora_default_edit()), because it is checked later when the link itself is themed (theme_islandora_datastream_replace_link()).

**Comment by DiegoPino** [comment]
@rosiel @jordandukart thanks. Merged.

**Pull request merged**
