### PR TITLE
Update README.md - Update Maintainer

### PR DESCRIPTION
**Pull request by manez**
# What does this Pull Request do?

Updates the Maintainer as part of the 7.x-1.8 Release Audit.

### CODE REVIEW

**Comment by manez** [comment]
Leaving the release pull off for now, because it's dragging more than just the template file along for the ride @dannylamb I suspect there's a headache here for you 😦

**Comment by DiegoPino** [comment]
@manez I will merge this, travis just got crazy but it is passing.

**Comment by DiegoPino** [comment]
@manez @dannylamb fixed the 7.x-1.8 branch, could you please make this pull against that branch now? Thanks

**Comment by manez** [comment]
@DiegoPino #655 for 7.x-1.8

**Pull request merged**
