### PR TITLE
ISLANDORA-1698 - update contributing.md

### PR DESCRIPTION
**Pull request by rnaughtonwk**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1698

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?
Added copy and link to the new code of conduct.

# Interested parties
@manez  @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by manez** [comment]
Note for other Committers: This is a trial balloon to get agreement on the wording and placement of this addition to CONTRIBUTING.md. Once this is approved and merged we can move on to release branches and the rest of Islandora.

**Comment by manez** [comment]
Oh, and @rnaughtonwk is covered by a cCLA 😄

**Comment by DiegoPino** [comment]
@manez restarted a stuck Travis Job. @rnaughtonwk could you address @manez 's comment =) Thanks!

**Comment by manez** [comment]
Thanks for the changes, @rnaughtonwk !

@Islandora/7-x-1-x-committers - this change is being proposed for all contributing.md files across islandora, so please review and comment if you don't agree. If there are no objections by Monday, I'll merge and we can proceed on the other modules.

**Comment by manez** [comment]
Oh and @DiegoPino should this be something we try to get on the 1.9 branch as well, or leave it for the next time to reduce the pull requests?

**Pull request merged**
