### PR TITLE
Has media view filter

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: https://github.com/Islandora/islandora-starter-site/issues/33

# What does this Pull Request do?

Adds a new View Filter that allows you to include or exclude nodes with a media with a given Media Use URI.

# What's new?

* Added a new View Filter
* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? No.

# How should this be tested?

* Pull in the PR
* Clear your Cache so Drupal can find it
* Create a new view of nodes (not necessarily the repository object, but that will be the most useful)
* Add the "Node has media use filter" filter and provide it with a URI, e.g. "http://pcdm.org/use#ThumbnailImage".
* Update the preview and it will only list nodes with a thumbnail media related to it.
* Update the filter with the "Negate" checkbox selected
* Update the preview and it will only list nodes _without_ a thumbnail media related to it.

# Documentation Status

* Does this change existing behaviour that's currently documented? No.
* Does this change require new pages or sections of documentation? Maybe?
* Who does this need to be documented for? Site managers.
* Associated documentation pull request(s): ___  or documentation issue ___

# Additional Notes:
View config that can be used for testing:
```yml
uuid: c8e796db-c226-407d-aa3c-f9963be42c16
langcode: en
status: true
dependencies:
  module:
    - islandora
    - node
    - user
id: test
label: TEST
module: views
description: ''
tag: ''
base_table: node_field_data
base_field: nid
display:
  default:
    id: default
    display_title: Default
    display_plugin: default
    position: 0
    display_options:
      title: TEST
      fields:
        title:
          id: title
          table: node_field_data
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: title
          plugin_id: field
          label: ''
          exclude: false
          alter:
            alter_text: false
            make_link: false
            absolute: false
            word_boundary: false
            ellipsis: false
            strip_tags: false
            trim: false
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: true
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      pager:
        type: mini
        options:
          offset: 0
          items_per_page: 10
          total_pages: null
          id: 0
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      access:
        type: perm
        options:
          perm: 'access content'
      cache:
        type: tag
        options: {  }
      empty: {  }
      sorts:
        created:
          id: created
          table: node_field_data
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: created
          plugin_id: date
          order: DESC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
          granularity: second
      arguments: {  }
      filters:
        status:
          id: status
          table: node_field_data
          field: status
          entity_type: node
          entity_field: status
          plugin_id: boolean
          value: '1'
          group: 1
          expose:
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
        islandora_has_media:
          id: islandora_has_media
          table: node_field_data
          field: islandora_has_media
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          plugin_id: islandora_node_has_media_use
          operator: '='
          value: ''
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          use_uri: 'http://pcdm.org/use#ThumbnailImage'
          negated: 1
        islandora_has_media_1:
          id: islandora_has_media_1
          table: node_field_data
          field: islandora_has_media
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          plugin_id: islandora_node_has_media_use
          operator: '='
          value: ''
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          use_uri: 'http://pcdm.org/use#ServiceFile'
          negated: 0
      filter_groups:
        operator: AND
        groups:
          1: AND
      style:
        type: default
      row:
        type: fields
      query:
        type: views_query
        options:
          query_comment: ''
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_tags: {  }
      relationships: {  }
      header: {  }
      footer: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url.query_args
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: 1
    display_options:
      display_extenders: {  }
      path: test
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url.query_args
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
```
The view could be cleaned up and enhanced and then added to `islandora_defaults/config/optional`.

# Interested parties
@rosiel, @wgilling, @amyrb

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Tagging @amyrb.

**Comment by ajstanley** [comment]
Just took this for a test drive, and it adds an amazing layer of functionality.  Nice work @seth-shaw-unlv !!!

**Comment by seth-shaw-unlv** [comment]
Thanks to @ajstanley for the push to turn the URI config textfield into a select box.

**Review by ajstanley — APPROVED** [review]
Runs exactly as it should.  This is going to make post-migration cleanup easier, and combined with VBOs will make mitigation for failed derivative calls a lot less work.

**Comment by seth-shaw-unlv** [comment]
Hold up. Selecting the "Expose this filter to visitors, to allow them to change it" option will cause a WSOD when looking at the View. (Also, "update preview" won't actually update, because of the crash.) We should probably find out how to fix or disable it first.

**Comment by ajstanley** [comment]
WSOD is because $form['islandora_has_media'] needs to be an array, and it's coming back as NULL.

**Comment by dannylamb** [comment]
This is still pretty amazing! I always considered it just a limitation of views, and you totally made it happen with a tiny piece in the right place. :1st_place_medal:

**Comment by seth-shaw-unlv** [comment]
@ajstanley & @dannylamb , I've killed off the ability to expose the filter. I consider this a temporary fix to prevent errors being thrown. We should eventually support this, but I'd like to get it in as is if y'all approve.

**Comment by ajstanley** [comment]
Yep, my approval still stands.  This is kind of a game-changer for validating migrations.

**Comment by seth-shaw-unlv** [comment]
@ajstanley, do you have the ability to merge? Or do we need an Admin like @rosiel or @dannylamb to do it?

**Comment by ajstanley** [comment]
Done and dusted.

**Pull request merged**
