### PR TITLE
Fixes Extracted Text not indexing in solr

### PR DESCRIPTION
**Pull request by dannylamb**
**JIRA Ticket**: Resolves https://github.com/Islandora/documentation/issues/1476

# What does this Pull Request do?

Manually triggers search re-indexing for nodes when their extracted text media are inserted or updated.

# What's new?

Brute forcing re-indexing in media insert and update hooks.

# How should this be tested?

## To confirm

- Ingest some paged content
- Go to a page and look at its extracted text file
- Search for something in the text
- Should get no results

Now apply this PR

- Ingest a new page
- Go to the page and look at its extracted text file
- Search for something in the text
- Should get results!

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by kayakr** [comment]
@dannylamb I noticed this issue last night also, so great to have a patch to try. I've applied the patch via composer and it works for a fresh new Repository Item but when I tried media update (e.g. by removing the PDF and adding a different PDF) I got a new Thumbnail Image but the extracted_text is still the text from the old file...

**Comment by dannylamb** [comment]
@kayakr Thanks so much for looking at this.  I've pushed up a tidier version of what I had before.  But hold up on testing it.  I'll walk through those steps and see why the extracted text isn't updating when replacing a file.  If I can fix it here I will.

**Comment by dannylamb** [comment]
So followed your steps and uploaded a new file to the "Original File" media, and got a new thumbnail but no extracted text or technical metadata.  Extracted text had nothing in the logs, but I did get this for the fits data:

```
Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[IslandoraConnector] [IslandoraConnector] [activemq://queue:islandora-connector-fits                                     ] [     41196]
[IslandoraConnector] [unmarshal9        ] [unmarshal[org.apache.camel.model.dataformat.JsonDataFormat@76ae54a5]          ] [         1]
[IslandoraConnector] [setProperty24     ] [setProperty[event]                                                            ] [         0]
[IslandoraConnector] [removeHeaders14   ] [removeHeaders[*]                                                              ] [         0]
[IslandoraConnector] [setHeader37       ] [setHeader[CamelHttpMethod]                                                    ] [         0]
[IslandoraConnector] [setHeader38       ] [setHeader[Accept]                                                             ] [         0]
[IslandoraConnector] [setHeader39       ] [setHeader[X-Islandora-Args]                                                   ] [         1]
[IslandoraConnector] [setHeader40       ] [setHeader[Apix-Ldp-Resource]                                                  ] [         0]
[IslandoraConnector] [setBody10         ] [setBody[simple{Simple: ${null}}]                                              ] [         0]
[IslandoraConnector] [to18              ] [{{derivative.service.url}}?connectionClose=true                               ] [     31165]
[IslandoraConnector] [removeHeaders15   ] [removeHeaders[*]                                                              ] [         0]
[IslandoraConnector] [setHeader41       ] [setHeader[Content-Location]                                                   ] [         0]
[IslandoraConnector] [setHeader42       ] [setHeader[CamelHttpMethod]                                                    ] [         0]
[IslandoraConnector] [toD11             ] [                                                                              ] [     10029]
[IslandoraConnector] [log20             ] [log                                                                           ] [         2]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/node/13/media/fits_technical_metadata/1 with statusCode: 400
```
Drupal logs are showing 

```
Symfony\Component\HttpKernel\Exception\HttpException: 'field_config' entity with ID 'media.fits_technical_metadata.fits_jhove_creating_application_' already exists. in Drupal\islandora\Controller\MediaSourceController->putToNode() (line 191 of /var/www/html/drupal/web/modules/contrib/islandora/src/Controller/MediaSourceController.php).
```

**Comment by dannylamb** [comment]
After debugging this pretty hard and running into everything from file permissions issues (www-data couldn't write sites/default/files), to transaction issues

```
Symfony\Component\HttpKernel\Exception\HttpException: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT savepoint_1 does not exist: ROLLBACK TO SAVEPOINT savepoint_1; Array ( ) in Drupal\islandora\Controller\MediaSourceController->putToNode() (line 191 of /var/www/html/drupal/web/modules/contrib/islandora/src/Controller/MediaSourceController.php).
```

At this point i'm going to rebuild my environment and try again to see if I can isolate the issues.  But one thing's for sure, you upload a new media and things go haywire.

It would be nice if another @Islandora/8-x-committers can try and recreate as well.  Just for basic sanity...

**Comment by seth-shaw-unlv** [comment]
I'll give it a spin.

**Pull request merged**
