### PR TITLE
Prevent Warning

### PR DESCRIPTION
**Pull request by jonathangreen**
# What does this Pull Request do?

I'm seeing this in my logs: 
```
Error: Call to a member function getTimestamp() on boolean in islandora_view_datastream_cache_check()
```

This checks that [DateTime::createFromFormat](http://php.net/manual/en/datetime.createfromformat.php) didn't return a boolean.

# What's new?

Should prevent warnings in logs from `islandora_view_datastream_cache_check()`

# How should this be tested?

* Check warnings before
* Check no warnings after

# Interested parties
@DiegoPino

### CODE REVIEW

**Comment by DiegoPino** [comment]
Ok, this makes all sense @jonathangreen. So:
This happens if $_SERVER['HTTP_IF_MODIFIED_SINCE'] exists but has no value?or the content is not a valid date?

If that happens, with your changes and you catch that, what will be the value of $return?

**Comment by jonathangreen** [comment]
I suspect I'm getting this when bots are either sending an empty header, or putting in bad values for the date. I just have the logs of it happening though, not actually what the value is. 

We set return to 200 here:
https://github.com/Islandora/islandora/pull/704/files#diff-002a1315b6c97d2d6512f550ca8672adR160

And we return the value here: 
https://github.com/Islandora/islandora/pull/704/files#diff-002a1315b6c97d2d6512f550ca8672adR215

So assuming none of the other conditions we check for apply, then we should return 200. We could short circuit the logic and directly return 200 if `HTTP_IF_MODIFIED_SINCE` is invalid, but it seemed best to follow the rest of the logic. I'm open to just returning 200 if you think thats better solution though.

**Comment by DiegoPino** [comment]
@jonathangreen, ok, t the use case. I see an issue if HTTP_IF_MODIFIED_SINCE exists but invalid and logic continues, I would say we can not trust the other headers that are being checked. If now HTTP_IF_UNMODIFIED_SINCE has same issue you will see again the error pop up, so i feel we should for security short circuit? not saying i'm sure but feels like once headers are wrong anything else can't be trusted. Your opinion here is important, i have a lot of bots blocked so i don't see this, only some  players in my list.

**Comment by whikloj** [comment]
Just wondering if the same logic should be applied to the results of 
```
$unmodified_since = DateTime::createFromFormat('D, d M Y H:i:s e', $_SERVER['HTTP_IF_UNMODIFIED_SINCE']);
```
on line 175?

**Comment by whikloj** [comment]
Oh 🤦‍♂️ I see @DiegoPino already mentions this.

**Comment by jonathangreen** [comment]
Thanks for the feedback guys. I updated the PR, so now it short circuits the rest of the logic and just returns if we have a bad header value for either: `HTTP_IF_UNMODIFIED_SINCE` or `HTTP_IF_MODIFIED_SINCE`.

**Comment by DiegoPino** [comment]
Will merge in 24, please follow up with a release pull, thanks!

**Comment by DiegoPino** [comment]
@jonathangreen merged both. Great contribution (as always!) 👏

**Comment by DiegoPino** [comment]
@jonathangreen i don't see a JIRA ticket here, could you point me to one? (needed for release stuff). Thanks

**Comment by jonathangreen** [comment]
https://jira.duraspace.org/browse/ISLANDORA-2212

**Pull request merged**
