### PR TITLE
Islandora-1943

### PR DESCRIPTION
**Pull request by jonathangreen**
Release version of this pull: 
https://github.com/Islandora/islandora/pull/670

### CODE REVIEW

**Comment by DiegoPino** [comment]
@jonathangreen this one looks different to #670. Want to sync before merging both?

**Comment by DiegoPino** [comment]
@jordandukart want to merge this one also after @jonathangreen updates it? thanks!

**Comment by jonathangreen** [comment]
@DiegoPino good call. Code review commits didn't end up here. Should be updated now.

**Comment by DiegoPino** [comment]
@jonathangreen cool. +8 −0 same on both. Happy release manager 😃 . @jordandukart in your trusted hands now to merge when you can/feel its ok

**Pull request merged**
