### PR TITLE
fix test runner and document travis scripts

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: n/a

Related to https://github.com/Islandora/islandora_solution_pack_audio/pull/148#issuecomment-462811400

# What does this Pull Request do?

Wraps the input to the `run_tests.sh` to ensure labels like Islandora Audio get captured correctly.

Also as some basic output of what is being run to ensure we are running the correct stuff.

# How should this be tested?

Let Travis run, but carefully inspect the results to ensure a pass is really a pass.

# Interested parties
@Islandora/7-x-1-x-committers, specifically @DiegoPino and @jonathangreen

### CODE REVIEW

**Comment by whikloj** [comment]
Not sure, we can't really test the other modules without this in 7.x, but someone might find something else out there. 🤷‍♂️

**Comment by jonathangreen** [comment]
I'm would like to merge this today in the interest of getting other modules working with travis, but I would like to hear if anyone has any objections. 

Pinging @Islandora/7-x-1-x-committers to see if anyone has an opinion that this should wait 24 hours. @dannylamb does this sound okay to you?

**Comment by DiegoPino** [comment]
I agree, but still, having 
```PHP 
function islandora_viewers_form($variable_id = NULL, $mimetype = NULL, $model = NULL) {
```
being called with either string or array for $mimetype in other modules will fail since. The PHP doc in that function is wrong because it states it should be a `string`. TBH, what is wrong is how we call it too.

**Comment by whikloj** [comment]
@DiegoPino Technically it won't fail because there is no type hint, if you like I can change the `$mimetype` PHPDoc to `string|array` as that will have no functional effect on the PR and be more correct.

**Comment by jonathangreen** [comment]
That sounds like a good solution to me @whikloj, but I will defer to @DiegoPino.

**Comment by DiegoPino** [comment]
@whikloj @jonathangreen ok, that works for me too.

**Comment by dannylamb** [comment]
If no one objects to waiving the 24 hr wait, please feel free to merge in the code once @DiegoPino's feedback has been addressed.

**Comment by whikloj** [comment]
@jonathangreen @DiegoPino @dannylamb Updated.

**Comment by jonathangreen** [comment]
This look good to you @DiegoPino? If so I'm going to merge when travis gives the green light.

**Comment by DiegoPino** [comment]
@jonathangreen cool with me. Almost green!

**Pull request merged**
