### PR TITLE
Spaces needed in error messages.

### PR DESCRIPTION
**Pull request by rosiel**
https://github.com/Islandora/documentation/issues/1637

* Other Relevant Links 
    * mentioned in https://github.com/Islandora-Devops/isle-dc/issues/117

# What does this Pull Request do?

Adds spaces, changes wording. 

# What's new?
 
Improved error messages, I hope?

# How should this be tested?

Does this make clearer error messages?

# Additional Notes:

* Maybe we should put some delimiters around the inserted text, such as:

`Error generating event: Could not locate taxonomy term with uri [https://projects.iq.harvard.edu/fits].`

That would be a coding style change, and could be implemented more broadly...

* I only got that one message, but I don't know if that means I should expect my derivative (without a  term) or not expect a derivative. Since it says "Error generating event" I'm guessing the former. Would it be bad form to add "Derivative generation for [FITS] could not proceed." or something? 

# Interested parties

@Islandora/8-x-committers

### CODE REVIEW

**Comment by rosiel** [comment]
I'm very confused by these Travis errors, do you know what's going on?

**Comment by dannylamb** [comment]
Sure do.  I have a PR to fix them.  But Travis is blocked there b/c it times out :sob:

**Comment by dannylamb** [comment]
https://github.com/Islandora/islandora/pull/799

**Review by dannylamb — APPROVED** [review]
:rocket:

**Pull request merged**
