### PR TITLE
fix for php 7.4 builds in github workflow

### PR DESCRIPTION
**Pull request by elizoller**
# What does this Pull Request do?

Fixes the github workflow for running tests. At least for PHP 7.4

# What's new?
* specifying the minimum stability for composer packages

# How should this be tested?
* if the tests run and pass then this is good.

# Interested parties
@Islandora/8-x-committers @mjordan

### CODE REVIEW

**Comment by whikloj** [comment]
@elizoller can you explain why this is necessary? Just asking for my own knowledge.

**Comment by elizoller** [comment]
the default is `stable` i believe. and certain modules don't have stable releases. ie. context which only has a beta release (https://www.drupal.org/project/context)

**Comment by elizoller** [comment]
@whikloj or @mjordan any interest in review? tests are green

**Comment by mjordan** [comment]
I can, but I'm now in calls all the way through to 2 PM Pacific. Can try to do it then or this evening.

**Comment by elizoller** [comment]
superseded by https://github.com/Islandora/islandora/pull/822/commits/d6ceebd82568c94b1b79c30f8c9e22274f58c6e9

**Comment by mjordan** [comment]
FYI I merged recent updates to 8.x-1.x into my PR branch and he build for PHP 7.4 drupal 9.1.5 is now passing.

**Pull request closed without merging**
