### PR TITLE
Issue 1521: Provide a way for repo admins to see RDF mappings

### PR DESCRIPTION
**Pull request by mjordan**
**Github issue**: https://github.com/Islandora/documentation/issues/1521

# What does this Pull Request do?

Adds a report listing all the 1) configured Drupal-field-to-RDF properties and 2) all of the external URIs associated with taxonomy terms.

# What's new?

* Adds a new controller at `admin/reports/islandora/rdf_mappings` that generates and renders the report
* Updates the `getUriFieldNamesForTerms()` function in the Islandora Utilities service

# How should this be tested?

1. Check out this branch. Within the `islandora` module directory:
   1. `git remote add mjordan https://github.com/mjordan/islandora.git`
   1. `git fetch mjordan`
   1. `git checkout issue-1521`
1. Clear your cache (`drush cr`)
1. Visit Admin > Reports > Field and term RDF mappings (refresh if you don't see this new item)
1. You should see the report listing fields and their RDF property mappings, and near the bottom, all taxonomies with terms that have external URIs / authority links. It's a long list.

# Additional Notes:

* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? Yes, a new item, "Field and term RDF mappings", appears in Drupal's "Reports" menu.
* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? Yes.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by manez** [comment]
Tested and all seems well!

Would it be possible to have the Taxonomy terms in the list link to their respective nodes?

**Comment by mjordan** [comment]
> Would it be possible to have the Taxonomy terms in the list link to their respective nodes?

Yes, it would. I'll do that.

**Comment by mjordan** [comment]
OK, terms are now linkable, e.g.:

Screenshot from 2020-05-30 10-49-19

**Comment by rosiel** [comment]
Great stuff Mark! 

I can imagine future asks such as sorting and filtering options, being able to find 'all fields that map to X' and cluster them together, adding the vocabulary id's in their headers, and making the headers collapsible (once someone puts an entire repo of 'people' in, it'll be scroll city). But a 1000% improvement over not having a report! Thank you!

**Comment by mjordan** [comment]
@rosiel thanks! All good suggestions, I hope having something basic like this gets people thinking about more useful features. Linking https://github.com/Islandora/documentation/issues/1529 for reference too.

**Comment by kayakr** [comment]
@mjordan @rosiel This is a nice report, but I've noticed a couple of things:
* it would be good to report on Type mapping, e.g. not just field level but entity to `pcdm:Object`, `rico:Record` etc.
* It only reports one mapping per field, but we have some fields with multiple mappings, e.g. `title` mapping to `dcterms:title` (appears in report) and `rico:name`(doesn't appear in report).

**Comment by mjordan** [comment]
@kayakr thanks! Since this is now merged, would you mind opening one or two separate issues? I'll take a look at both.

**Pull request merged**
